"""empty message

Revision ID: 17f9c3a448f0
Revises: 215971102a45
Create Date: 2020-06-22 16:56:15.835097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f9c3a448f0'
down_revision = '215971102a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('assigned_dev', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'assigned_dev')
    # ### end Alembic commands ###
