"""empty message

Revision ID: 8ff11ca0a6ee
Revises: d483c3d8ea7a
Create Date: 2020-07-07 15:00:22.362789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ff11ca0a6ee'
down_revision = 'd483c3d8ea7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comment', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('assigned_dev', sa.String(length=120), nullable=True))
    op.alter_column('ticket', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('ticket', 'files')
    op.add_column('ticket_history', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_history', 'date')
    op.add_column('ticket', sa.Column('files', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('ticket', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('ticket', 'assigned_dev')
    op.drop_column('comment', 'date')
    op.drop_table('ticket_image')
    # ### end Alembic commands ###
