"""empty message

Revision ID: c5a3750bcb39
Revises: 17f9c3a448f0
Create Date: 2020-07-07 14:33:53.512365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a3750bcb39'
down_revision = '17f9c3a448f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comment', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('ticket', 'files')
    op.add_column('ticket_history', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_history', 'date')
    op.add_column('ticket', sa.Column('files', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('comment', 'date')
    op.drop_table('ticket_image')
    # ### end Alembic commands ###
