"""empty message

Revision ID: f0e15bb7dfe4
Revises: 8ff11ca0a6ee
Create Date: 2020-07-13 07:36:00.145221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0e15bb7dfe4'
down_revision = '8ff11ca0a6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_image')
    op.add_column('comment', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'image')
    op.create_table('ticket_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name='ticket_image_ticket_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ticket_image_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ticket_image_pkey')
    )
    # ### end Alembic commands ###
